gretting:
  name: Dev directory git

spring:
  jpa:
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://192.168.101.11/postgres?user=postgres&password=somePassword
    validationQuery: SELECT 1

